name: latihan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0 # Tambahkan ini agar bisa digunakan di code Anda
  sembast: ^3.6.0
  sembast_web: ^2.3.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^24.2.3
  translator: ^0.1.7
  flutter_tts: ^3.8.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# PINDAHKAN KE SINI (Sejajar dengan dependencies/dev_dependencies)
dependency_overrides:
  http: ^1.1.0

flutter:
  uses-material-design: true